# Generated by Django 4.2 on 2023-07-20 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='materialprovide',
        ),
        migrations.DeleteModel(
            name='MaterialProvide',
        ),
    ]
